### ISSUE TITLE
我测试了，翻墙失败

### ISSUE THREAD

**Issue by luckypoem** [cctiger36/socks-tunnel-demo#1]
hi。
服务器端：
root@VM:~/socks-tunnel-demo-by-cctiger36# ruby remote.rb
Starting server at 0.0.0.0:8082

客户端（mac):
yudeMacBook-Air:socks-tunnel-demo-master brite$ ruby local.rb
Start socks5 at 127.0.0.1:8081

然后我设置浏览器的socks5代理为127.0.0.1:8081,但是翻墙失败。
是否要把local.rb的第105行的REMOTE_SERVER_HOST, REMOTE_SERVER_PORT改为我服务器的ip和端口？

**Comment by luckypoem** [comment]
hi.
我测试了，如果改了的话，反而出错。我改回去了。
这样就不知道为何翻墙失败了。

**Comment by cctiger36** [comment]
试了一下，是上来握手的时候有 bug，unpack 返回的是个数组。现在应该能连通了。
还有同学这玩意儿只是写着玩的，别真的拿来翻墙啊。数据没有加密的，如果要用起码自己加一个AES，或者等我哪天再心血来潮把这部分补上😝

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:socks-tunnel-demo brite$ ruby local.rb
Start socks5 at 127.0.0.1:8081
local.rb:129:in `reply_data': undefined method`to_h' for #Array:0x007fa8b3957b18 (NoMethodError)
    from local.rb:104:in `do_command'
    from local.rb:32:in`block (2 levels) in post_init'
    from local.rb:32:in `loop'
    from local.rb:32:in`block in post_init'
yudeMacBook-Air:socks-tunnel-demo brite$

反而出错了，怎么回事呢？

**Comment by cctiger36** [comment]
Array#to_h 是 ruby 2.2 开始才有的，你可以升级一下试试

**Comment by luckypoem** [comment]
运行brew install ruby,升级了。
yudeMacBook-Air:socks-tunnel-demo brite$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
yudeMacBook-Air:socks-tunnel-demo brite$
yudeMacBook-Air:socks-tunnel-demo brite$ ruby local.rb
Start socks5 at 127.0.0.1:8081

设置浏览器的socks5代理为127.0.0.1:8081后，我并未访问被封的网站，而是访问http://ipaddress.com ，但是该网站根本就打不开。即使数据没有加密，那也应该能访问被封的网站吧。怎么访问不了呢？你自己测试过吗？
或者哪天你心血来潮了，加密了数据，就能翻墙了吗？期待你早日心血来潮！

我服务器上的ruby依旧是2.0.0版，没影响吧？

**Comment by cctiger36** [comment]
我自己测试过是可以连通的。
local.rb 里面的 REMOTE_SERVER_HOST 和 REMOTE_SERVER_PORT 有没有改成你服务器的IP和端口？服务器的端口有没有开放？
或者你可以把 remote.rb 先放在本地跑一下试试，看看到底是服务器的问题还是其他的问题。

**Comment by luckypoem** [comment]
hi。
原来是local.rb 里面的 REMOTE_SERVER_HOST没有改成我服务器的IP。现在可以翻墙了。访问 ipleak.net也并未显示我的本地ip.

你这个代码未加密，仍可用来翻墙。估计是混淆了流量所致吗？就像https://github.com/lerry/balan-proxy所作的那样。

**Comment by luckypoem** [comment]
hi.

如何在remote.rb里面，设置仅限本机（localhost)连接？现在我运行你这个程序（ruby remote.rb)的vps被服务商suspend,估计是带宽超标所致。运行nohup ruby remote.rb > /dev/null &后，我的vps_ip:8082是否就成为了一个公共的socks proxy server?然后被那些扫描互联网上的公共的socks proxy server的网站发现了，从而把我的vps_ip:8082公布在其网站上，从而导致我的vps的bandwidth很快耗尽，从而我的vps被服务商suspend？我很怀疑是这个原因。那么如何在remote.rb里面，设置仅限本机（localhost)连接呢？
谢谢回复

**Comment by cctiger36** [comment]
加了几行代码限制只有自己的 IP 可以连接 Remote，另外前两天把加密的部分补上了，你可以试试

**Comment by luckypoem** [comment]
之前未加密时，可翻墙，但昨天开始不行了。加密部分加上后，确实不错，又可以翻墙了。不过在remote.rb里，你加了哪几行代码？我没看出来

**Comment by luckypoem** [comment]
我用你现在这个“加了几行代码限制只有自己的 IP 可以连接 Remote”的版本反而翻墙失败。我觉得你2天前那个版本更好用，而且config.rb里面有设置密码的选项，这样别人是连接不上服务器端的，因此不用再“加几行代码限制只有自己的 IP 可以连接 Remote“了吧。
我用2天前的状态的代码可以成功翻墙。所以可否把你的代码roll back到2天前的状态呢？

**Comment by cctiger36** [comment]
看了一下的确有问题，我把限制IP的部分 Revert 掉了。

**Comment by cctiger36** [comment]
还有比较简单限制IP的方法是你可以在 remote 前面加个 nginx，用 nginx 做 TCP 的转发，然后在 nginx  里写限制。

**Comment by luckypoem** [comment]
hi。
“config.rb里面有设置密码的选项，这样别人是连接不上我的服务器端的”－我说的对吗？
如果对的话，就不用限制ip了吧？反正别人连接不上我的服务器端。

**Comment by cctiger36** [comment]
别人不知道密码的话是不能正常使用的，但是他们可以探测到你的端口，然后不断发送垃圾数据进行 DOS 攻击。当然如果没碰上这么无聊的人限不限制IP都无所谓。

**Comment by luckypoem** [comment]
hi.

**Comment by luckypoem** [comment]
hi.

用nohup ruby remote.rb > /dev/null &固然可以让服务器端在后台运行，但是搞不了多久，服务器端就退出了。那么如何让服务器端长久地在后台运行？如何让它以daemon方式运行？
谢谢你

**Comment by cctiger36** [comment]
不好意思忘了回了
我已经把代码打包成gem了，里面自带了daemon选项，有兴趣的话可以试一下
https://github.com/cctiger36/socks_tunnel

**Comment by luckypoem** [comment]
hi.
在https://github.com/cctiger36/socks_tunnel 里，你这个daemon选项是怎么实现的？任何在前台运行的程序都可以daemon化吗？有把前台运行的程序daemon化的通用办法吗
